//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemFunctionalCategory
    {
        public ItemFunctionalCategory()
        {
            this.Items = new HashSet<Item>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Category { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
