//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationEvent
    {
        public ReservationEvent()
        {
            this.ReservedItems = new HashSet<ReservedItem>();
        }
    
        public long Id { get; set; }
        public string Indication { get; set; }
        public string EventState { get; set; }
        public System.DateTime PlannedStartDate { get; set; }
        public System.DateTime PlannedEndDate { get; set; }
        public long Reserver { get; set; }
    
        public virtual ICollection<ReservedItem> ReservedItems { get; set; }
    }
}
