//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestorationEvent
    {
        public RestorationEvent()
        {
            this.RestoredItems = new HashSet<RestoredItem>();
        }
    
        public long Id { get; set; }
        public string Indication { get; set; }
        public string EventState { get; set; }
        public System.DateTime PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public long Restorer { get; set; }
    
        public virtual ICollection<RestoredItem> RestoredItems { get; set; }
    }
}
