//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestoredItem
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> RealStartDate { get; set; }
        public Nullable<System.DateTime> RealEndDate { get; set; }
        public long UsedItem { get; set; }
        public long InitialState { get; set; }
        public Nullable<long> ReturnState { get; set; }
        public long Restoration { get; set; }
    
        public virtual RestorationEvent RestorationEvent { get; set; }
    }
}
