//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_invoices
    {
        public long InvoiceId { get; set; }
        public long InvoicePhaseNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal InvoiceCost { get; set; }
        public int InvoiceDepreciation { get; set; }
        public string InvoiceIndication { get; set; }
        public string InvoiceScan { get; set; }
        public string ProviderName { get; set; }
    }
}
