//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_packs
    {
        public long PackId { get; set; }
        public string PackName { get; set; }
        public string PackDescription { get; set; }
        public string ItemCategory { get; set; }
        public string ItemFunctionalCategory { get; set; }
        public Nullable<long> ItemEAN13 { get; set; }
        public string ItemBrand { get; set; }
        public string ItemReference { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<long> ItemCost { get; set; }
        public string ItemStateNow { get; set; }
        public Nullable<sbyte> ItemIsUsable { get; set; }
        public Nullable<sbyte> ItemIsConsumable { get; set; }
    }
}
