//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_items
    {
        public long ItemId { get; set; }
        public string ItemCategory { get; set; }
        public string ItemFunctionalCategory { get; set; }
        public Nullable<long> ItemEAN13 { get; set; }
        public string ItemBrand { get; set; }
        public string ItemReference { get; set; }
        public string ItemDescription { get; set; }
        public string ItemPicture { get; set; }
        public string ItemStateNow { get; set; }
        public bool ItemIsUsable { get; set; }
        public bool ItemIsConsumable { get; set; }
        public bool ItemIsReservable { get; set; }
        public long InvoicePhaseNumber { get; set; }
    }
}
