//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_reservations
    {
        public long ReservationId { get; set; }
        public string ReservationEventState { get; set; }
        public string ReservationIndication { get; set; }
        public string ReserverEmail { get; set; }
        public int ReserverWallet { get; set; }
        public string ReserverHistoric { get; set; }
        public System.DateTime PlannedStartDate { get; set; }
        public Nullable<System.DateTime> RealStartDate { get; set; }
        public System.DateTime PlannedEndDate { get; set; }
        public Nullable<System.DateTime> RealEndDate { get; set; }
        public string UsedPack { get; set; }
        public Nullable<long> ItemEAN13 { get; set; }
        public string ItemBrand { get; set; }
        public string ItemReference { get; set; }
        public string ItemDescription { get; set; }
        public long ItemCost { get; set; }
        public string ItemStateBefore { get; set; }
        public string ItemStateAfter { get; set; }
        public string ItemStateNow { get; set; }
        public bool ItemIsUsable { get; set; }
        public bool ItemIsConsumable { get; set; }
    }
}
