//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_accounts
    {
        public long AccountId { get; set; }
        public string AccountCategory { get; set; }
        public string AccountDivision { get; set; }
        public string AccountFirstName { get; set; }
        public string AccountLastName { get; set; }
        public string AccountEmail { get; set; }
        public string AccountPhone { get; set; }
        public string AccountAdress { get; set; }
        public string AccountHistoric { get; set; }
        public int AccountWallet { get; set; }
        public string AccountPermissionLevel { get; set; }
        public string DivisionReservationRight { get; set; }
        public string AccountPortrait { get; set; }
    }
}
