//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Items
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRestoration
    {
        public long Id { get; set; }
        public System.DateTime BeginningDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public long Repaired { get; set; }
        public long Repairer { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
