//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Items
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMainCategory
    {
        public ItemMainCategory()
        {
            this.ItemSubCategories = new HashSet<ItemSubCategory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ItemSubCategory> ItemSubCategories { get; set; }
    }
}
