//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Items
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemRestorations = new HashSet<ItemRestoration>();
        }
    
        public long Id { get; set; }
        public Nullable<long> EAN13 { get; set; }
        public string Reference { get; set; }
        public long ReservationCost { get; set; }
        public bool Consumable { get; set; }
        public bool Reservable { get; set; }
        public string Description { get; set; }
        public string PicturePath { get; set; }
        public long Brand { get; set; }
        public long RelatedInvoice { get; set; }
        public long SubCategory { get; set; }
        public long CurrentState { get; set; }
    
        public virtual ItemBrand ItemBrand { get; set; }
        public virtual ItemSubCategory ItemSubCategory { get; set; }
        public virtual ItemState ItemState { get; set; }
        public virtual ICollection<ItemRestoration> ItemRestorations { get; set; }
    }
}
