//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts.Accounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Historic { get; set; }
        public int Wallet { get; set; }
        public bool Active { get; set; }
        public bool Banned { get; set; }
        public string PicturePath { get; set; }
        public long SubCategory { get; set; }
    
        public virtual AccountSubCategory AccountSubCategory { get; set; }
    }
}
