//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts.Accounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDivision
    {
        public AccountDivision()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ReservationMod { get; set; }
        public long Category { get; set; }
    
        public virtual AccountCategory AccountCategory { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
