//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts.Accounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMainCategory
    {
        public AccountMainCategory()
        {
            this.AccountSubCategories = new HashSet<AccountSubCategory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AccountSubCategory> AccountSubCategories { get; set; }
    }
}
