//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Accounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSubCategory
    {
        public AccountSubCategory()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long MainCategory { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual AccountMainCategory AccountMainCategory { get; set; }
    }
}
