//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Invoices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long Id { get; set; }
        public long PhaseNumber { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal PurchaseCost { get; set; }
        public int Depreciation { get; set; }
        public string ScanPath { get; set; }
        public long Provider { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
