//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationPlanning
    {
        public ReservationPlanning()
        {
            this.ReservationEvents = new HashSet<ReservationEvent>();
            this.ReservationItems = new HashSet<ReservationItem>();
        }
    
        public long Id { get; set; }
        public System.DateTime BeginningDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
    
        public virtual ICollection<ReservationEvent> ReservationEvents { get; set; }
        public virtual ICollection<ReservationItem> ReservationItems { get; set; }
    }
}
