using ITI.PixLogic.DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace ITI.PixLogic.WinApp
{
    public partial class Accounts : Form
    {
        
        pldb_entities ple = new pldb_entities();
        public Accounts()
        {
            InitializeComponent();
            Accounts_Load();
        }

        private void Accounts_Load()
        {
            ple.accounts.Load();
            accountBindingSource.DataSource = ple.accounts.Local.ToBindingList();    
        }

        private void save_button_Click(object sender, EventArgs e)
        {
            this.Validate();

            // Save the changes to the database. 
            this.ple.SaveChanges();

            // Refresh the controls to show the values          
            // that were generated by the database. 
            this.dataGridViewUsers.Refresh();
        }

        private void button_back_Click(object sender, EventArgs e)
        {
            new Home().Show();
            this.Close();
        }

        private void button_add_Click(object sender, EventArgs e)
        {
            new AddUserAccountForm().Show();
            this.Close();
        }
    }
}
