using ITI.PixLogic.DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace ITI.PixLogic.WinApp
{
    public partial class Accounts : Form
    {
        
        pldb_entities ple = new pldb_entities();
        public Accounts()
        {
            InitializeComponent();
            Accounts_Load();
        }

        private void Accounts_Load()
        {
            ple.accounts.Load();
            accountBindingSource.DataSource = ple.accounts.Local.ToBindingList();    
        }

        private void save_button_Click(object sender, EventArgs e)
        {
            this.Validate();

            // Save the changes to the database. 
            this.ple.SaveChanges();

            // Refresh the controls to show the values          
            // that were generated by the database. 
            this.dataGridViewUsers.Refresh();
        }

        private void button_back_Click(object sender, EventArgs e)
        {
            new Home().Show();
            this.Close();
        }

        private void button_add_Click(object sender, EventArgs e)
        {
            new AddUserAccountForm().Show();
            this.Close();
        }

        private void button_delete_Click(object sender, EventArgs e)
        {
            if (dataGridViewUsers.SelectedRows.Count == 0 || dataGridViewUsers.SelectedRows.Contains(dataGridViewUsers.Rows[dataGridViewUsers.RowCount - 1]))
            //if (consumablesdataGridView.SelectedRows[0].Cells[0].Value == null)
            {
                MessageBox.Show("Veuillez selectionner une ligne a supprimer");
            }


            else
            {
                var toBeDeleted = (long)dataGridViewUsers.SelectedRows[0].Cells[0].Value;
                var UserData = ple.accounts.First(c => c.id == toBeDeleted);
                ple.accounts.Remove(UserData);
                ple.SaveChanges();
                ple.accounts.Load();
                dataGridViewUsers.DataSource = ple.accounts.Local.ToBindingList();
                
            }
           
        }

        private void button_modify_Click(object sender, EventArgs e)
        {
            var toBeModify = (long)dataGridViewUsers.SelectedRows[0].Cells[0].Value;
            var UserData = ple.accounts.First(c => c.id == toBeModify);
            new ModifyUserAccountcs().Show();
            this.Close();
        }
    }
}
