//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts.Events
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventsEntity : DbContext
    {
        public EventsEntity()
            : base("name=EventsEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Planning> Plannings { get; set; }
        public virtual DbSet<ReservationEvent> ReservationEvents { get; set; }
        public virtual DbSet<ReservationItem> ReservationItems { get; set; }
        public virtual DbSet<RestorationEvent> RestorationEvents { get; set; }
        public virtual DbSet<RestorationItem> RestorationItems { get; set; }
    }
}
