//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts.Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestorationEvent
    {
        public RestorationEvent()
        {
            this.RestorationItems = new HashSet<RestorationItem>();
        }
    
        public long Id { get; set; }
        public string Indication { get; set; }
        public bool TakenOut { get; set; }
        public long InitialPlanning { get; set; }
        public long Restorer { get; set; }
    
        public virtual Planning Planning { get; set; }
        public virtual ICollection<RestorationItem> RestorationItems { get; set; }
    }
}
