//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts.Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservationexport
    {
        public long Numéro_de_la_réservation { get; set; }
        public string Personne_ayant_réservée { get; set; }
        public System.DateTime Début_estimé_de_la_réservation { get; set; }
        public System.DateTime Début_réel_de_la_réservation { get; set; }
        public System.DateTime Fin_estimée_de_la_réservation { get; set; }
        public System.DateTime Fin_réel_de_la_réservation { get; set; }
        public string Nom_du_pack_utilisé { get; set; }
        public string Marque { get; set; }
        public string Référence { get; set; }
        public string Etat_avant_la_réservation { get; set; }
        public string Etat_après_la_réservation { get; set; }
        public string Etat_actuel { get; set; }
    }
}
