//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contexts.Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationPlanning
    {
        public long Id { get; set; }
        public System.DateTime BeginningDate { get; set; }
        public System.DateTime EndingDate { get; set; }
    }
}
