//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Packs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagedItemCategory
    {
        public long Id { get; set; }
        public long UsedCategory { get; set; }
        public long UsedPack { get; set; }
    
        public virtual Pack Pack { get; set; }
    }
}
