//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL.Contextes.Packs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack
    {
        public Pack()
        {
            this.PackagedItems = new HashSet<PackagedItem>();
            this.PackagedItemCategories = new HashSet<PackagedItemCategory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Reservable { get; set; }
    
        public virtual ICollection<PackagedItem> PackagedItems { get; set; }
        public virtual ICollection<PackagedItemCategory> PackagedItemCategories { get; set; }
    }
}
