//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_sub_categories
    {
        public accounts_sub_categories()
        {
            this.accounts = new HashSet<account>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> main_category { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual accounts_main_categories accounts_main_categories { get; set; }
    }
}
