//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> wallet { get; set; }
        public Nullable<int> sub_category { get; set; }
    
        public virtual accounts_sub_categories accounts_sub_categories { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
