//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public long id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public bool active { get; set; }
        public int wallet { get; set; }
        public long sub_category { get; set; }
    
        public virtual accounts_sub_categories accounts_sub_categories { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
