//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_sub_categories
    {
        public accounts_sub_categories()
        {
            this.accounts = new HashSet<account>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long main_category { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual accounts_main_categories accounts_main_categories { get; set; }
    }
}
