//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingEntityConnectionSettings : DbContext
    {
        public AccountingEntityConnectionSettings()
            : base("name=AccountingEntityConnectionSettings")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<companies> companies { get; set; }
        public virtual DbSet<contacts> contacts { get; set; }
        public virtual DbSet<invoices> invoices { get; set; }
        public virtual DbSet<repairs> repairs { get; set; }
    }
}
