//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitalized_sub_categories
    {
        public capitalized_sub_categories()
        {
            this.capitalized = new HashSet<capitalized>();
            this.capitalized_categories_in_packs = new HashSet<capitalized_categories_in_packs>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long main_category { get; set; }
    
        public virtual ICollection<capitalized> capitalized { get; set; }
        public virtual ICollection<capitalized_categories_in_packs> capitalized_categories_in_packs { get; set; }
        public virtual capitalized_main_categories capitalized_main_categories { get; set; }
    }
}
