//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitalized_states
    {
        public capitalized_states()
        {
            this.capitalized = new HashSet<capitalized>();
            this.capitalized_reserved = new HashSet<capitalized_reserved>();
            this.capitalized_reserved1 = new HashSet<capitalized_reserved>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool reservable { get; set; }
    
        public virtual ICollection<capitalized> capitalized { get; set; }
        public virtual ICollection<capitalized_reserved> capitalized_reserved { get; set; }
        public virtual ICollection<capitalized_reserved> capitalized_reserved1 { get; set; }
    }
}
