//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitalized_states
    {
        public capitalized_states()
        {
            this.capitalized = new HashSet<capitalized>();
            this.capitalized_reserved = new HashSet<capitalized_reserved>();
            this.capitalized_reserved1 = new HashSet<capitalized_reserved>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool reservable { get; set; }
    
        public virtual ICollection<capitalized> capitalized { get; set; }
        public virtual ICollection<capitalized_reserved> capitalized_reserved { get; set; }
        public virtual ICollection<capitalized_reserved> capitalized_reserved1 { get; set; }
    }
}
