//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitalized
    {
        public capitalized()
        {
            this.capitalized_items_in_packs = new HashSet<capitalized_items_in_packs>();
            this.capitalized_reserved = new HashSet<capitalized_reserved>();
            this.repairs = new HashSet<repair>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string picture { get; set; }
        public Nullable<long> ean13 { get; set; }
        public Nullable<decimal> reservation_cost { get; set; }
        public Nullable<int> sub_category { get; set; }
        public Nullable<int> invoice { get; set; }
        public Nullable<int> current_state { get; set; }
    
        public virtual capitalized_states capitalized_states { get; set; }
        public virtual invoice invoice1 { get; set; }
        public virtual ICollection<capitalized_items_in_packs> capitalized_items_in_packs { get; set; }
        public virtual ICollection<capitalized_reserved> capitalized_reserved { get; set; }
        public virtual capitalized_sub_categories capitalized_sub_categories { get; set; }
        public virtual ICollection<repair> repairs { get; set; }
    }
}
