//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitalized_reserved
    {
        public long id { get; set; }
        public Nullable<System.DateTime> real_return_date { get; set; }
        public long reservation { get; set; }
        public long item { get; set; }
        public long initial_state { get; set; }
        public Nullable<long> return_state { get; set; }
    
        public virtual reservations reservations { get; set; }
    }
}
