//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitalized_sub_categories
    {
        public capitalized_sub_categories()
        {
            this.capitalizeds = new HashSet<capitalized>();
            this.capitalized_categories_in_packs = new HashSet<capitalized_categories_in_packs>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> main_category { get; set; }
    
        public virtual ICollection<capitalized> capitalizeds { get; set; }
        public virtual ICollection<capitalized_categories_in_packs> capitalized_categories_in_packs { get; set; }
        public virtual capitalized_main_categories capitalized_main_categories { get; set; }
    }
}
