//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitalized_items_in_packs
    {
        public long id { get; set; }
        public long item { get; set; }
        public long pack { get; set; }
    
        public virtual capitalized capitalized { get; set; }
        public virtual specifics_packs specifics_packs { get; set; }
    }
}
