//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.contacts = new HashSet<contact>();
            this.invoices = new HashSet<invoice>();
            this.repairs = new HashSet<repair>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> phone { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<contact> contacts { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual ICollection<repair> repairs { get; set; }
    }
}
