//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class companies
    {
        public companies()
        {
            this.contacts = new HashSet<contacts>();
            this.invoices = new HashSet<invoices>();
            this.repairs = new HashSet<repairs>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> phone { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<contacts> contacts { get; set; }
        public virtual ICollection<invoices> invoices { get; set; }
        public virtual ICollection<repairs> repairs { get; set; }
    }
}
