//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.contacts = new HashSet<contact>();
            this.invoices = new HashSet<invoice>();
            this.repairs = new HashSet<repair>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> phone { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<contact> contacts { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual ICollection<repair> repairs { get; set; }
    }
}
