//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumable
    {
        public consumable()
        {
            this.consumables_items_in_packs = new HashSet<consumables_items_in_packs>();
            this.consumables_reserved = new HashSet<consumables_reserved>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long reservation_cost { get; set; }
        public long sub_category { get; set; }
        public long invoice { get; set; }
        public long current_state { get; set; }
    
        public virtual consumables_states consumables_states { get; set; }
        public virtual invoice invoice1 { get; set; }
        public virtual ICollection<consumables_items_in_packs> consumables_items_in_packs { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved { get; set; }
        public virtual consumables_sub_categories consumables_sub_categories { get; set; }
    }
}
