//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumables_states
    {
        public consumables_states()
        {
            this.consumables = new HashSet<consumables>();
            this.consumables_reserved = new HashSet<consumables_reserved>();
            this.consumables_reserved1 = new HashSet<consumables_reserved>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool reservable { get; set; }
    
        public virtual ICollection<consumables> consumables { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved1 { get; set; }
    }
}
