//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumables_reserved
    {
        public int id { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<int> reservation { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> initial_state { get; set; }
        public Nullable<int> return_state { get; set; }
    
        public virtual consumable consumable { get; set; }
        public virtual consumables_states consumables_states { get; set; }
        public virtual reservation reservation1 { get; set; }
        public virtual consumables_states consumables_states1 { get; set; }
    }
}
