//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumables_sub_categories
    {
        public consumables_sub_categories()
        {
            this.consumables = new HashSet<consumables>();
            this.consumables_categories_in_packs = new HashSet<consumables_categories_in_packs>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long main_category { get; set; }
    
        public virtual ICollection<consumables> consumables { get; set; }
        public virtual ICollection<consumables_categories_in_packs> consumables_categories_in_packs { get; set; }
        public virtual consumables_main_categories consumables_main_categories { get; set; }
    }
}
