//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumables_states
    {
        public consumables_states()
        {
            this.consumables = new HashSet<consumables>();
            this.consumables_reserved = new HashSet<consumables_reserved>();
            this.consumables_reserved1 = new HashSet<consumables_reserved>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool reservable { get; set; }
    
        public virtual ICollection<consumables> consumables { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved1 { get; set; }
    }
}
