//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumable
    {
        public consumable()
        {
            this.consumables_items_in_packs = new HashSet<consumables_items_in_packs>();
            this.consumables_reserved = new HashSet<consumables_reserved>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> reservation_cost { get; set; }
        public Nullable<int> sub_category { get; set; }
        public Nullable<int> invoice { get; set; }
        public Nullable<int> current_state { get; set; }
    
        public virtual consumables_states consumables_states { get; set; }
        public virtual invoice invoice1 { get; set; }
        public virtual ICollection<consumables_items_in_packs> consumables_items_in_packs { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved { get; set; }
        public virtual consumables_sub_categories consumables_sub_categories { get; set; }
    }
}
