//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumables_categories_in_packs
    {
        public long id { get; set; }
        public long category { get; set; }
        public long pack { get; set; }
    
        public virtual consumables_sub_categories consumables_sub_categories { get; set; }
        public virtual generics_packs generics_packs { get; set; }
    }
}
