//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumables_sub_categories
    {
        public consumables_sub_categories()
        {
            this.consumables = new HashSet<consumables>();
            this.consumables_categories_in_packs = new HashSet<consumables_categories_in_packs>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long main_category { get; set; }
    
        public virtual ICollection<consumables> consumables { get; set; }
        public virtual ICollection<consumables_categories_in_packs> consumables_categories_in_packs { get; set; }
        public virtual consumables_main_categories consumables_main_categories { get; set; }
    }
}
