//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public long id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<long> phone { get; set; }
        public string email { get; set; }
        public long company { get; set; }
    
        public virtual company company1 { get; set; }
    }
}
