//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.capitalizeds = new HashSet<capitalized>();
            this.consumables = new HashSet<consumable>();
        }
    
        public long id { get; set; }
        public System.DateTime purchase_date { get; set; }
        public decimal purchase_cost { get; set; }
        public int annual_depreciation_rate { get; set; }
        public long phase_number { get; set; }
        public string description { get; set; }
        public long company { get; set; }
    
        public virtual ICollection<capitalized> capitalizeds { get; set; }
        public virtual company company1 { get; set; }
        public virtual ICollection<consumable> consumables { get; set; }
    }
}
