//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.capitalizeds = new HashSet<capitalized>();
            this.consumables = new HashSet<consumable>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<decimal> purchase_cost { get; set; }
        public Nullable<int> annual_depreciation_rate { get; set; }
        public Nullable<long> phase_number { get; set; }
        public Nullable<int> company { get; set; }
    
        public virtual ICollection<capitalized> capitalizeds { get; set; }
        public virtual company company1 { get; set; }
        public virtual ICollection<consumable> consumables { get; set; }
    }
}
