//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PacksEntity : DbContext
    {
        public PacksEntity()
            : base("name=PacksEntityConnectionSettings")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<capitalized_categories_in_packs> capitalized_categories_in_packs { get; set; }
        public virtual DbSet<capitalized_items_in_packs> capitalized_items_in_packs { get; set; }
        public virtual DbSet<consumables_categories_in_packs> consumables_categories_in_packs { get; set; }
        public virtual DbSet<consumables_items_in_packs> consumables_items_in_packs { get; set; }
        public virtual DbSet<packs> packs { get; set; }
    }
}
