//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservations
    {
        public reservations()
        {
            this.capitalized_reserved = new HashSet<capitalized_reserved>();
            this.consumables_reserved = new HashSet<consumables_reserved>();
        }
    
        public long id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime estimated_return_date { get; set; }
        public bool confirmed { get; set; }
        public bool taken_out { get; set; }
        public long account { get; set; }
    
        public virtual ICollection<capitalized_reserved> capitalized_reserved { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved { get; set; }
    }
}
