//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReservationsEntity : DbContext
    {
        public ReservationsEntity()
            : base("name=ReservationsEntityConnectionSettings")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<capitalized_reserved> capitalized_reserved { get; set; }
        public virtual DbSet<consumables_reserved> consumables_reserved { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
    }
}
