//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public reservation()
        {
            this.capitalized_reserved = new HashSet<capitalized_reserved>();
            this.consumables_reserved = new HashSet<consumables_reserved>();
        }
    
        public long id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime estimated_return_date { get; set; }
        public bool confirmed { get; set; }
        public bool taken_out { get; set; }
        public long account { get; set; }
    
        public virtual account account1 { get; set; }
        public virtual ICollection<capitalized_reserved> capitalized_reserved { get; set; }
        public virtual ICollection<consumables_reserved> consumables_reserved { get; set; }
    }
}
