//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.PixLogic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class specifics_packs
    {
        public specifics_packs()
        {
            this.capitalized_items_in_packs = new HashSet<capitalized_items_in_packs>();
            this.consumables_items_in_packs = new HashSet<consumables_items_in_packs>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<capitalized_items_in_packs> capitalized_items_in_packs { get; set; }
        public virtual ICollection<consumables_items_in_packs> consumables_items_in_packs { get; set; }
    }
}
